### ISSUE TITLE
The Latency graph is plotting the wrong data

### ISSUE THREAD

**Issue by dean-long** [ebarlas/project-loom-comparison#1]
Looks like a typo, using 'rss' instead of 'latency'.

**Comment by ebarlas** [comment]
Thank you, @dean-long! I'll address that right now...

**Comment by ebarlas** [comment]
Fixed: https://github.com/ebarlas/project-loom-comparison/commit/1869f2084060e8757e470e8bb1ad84d4ccd9ad3e

**Comment by dean-long** [comment]
Thanks!
